### ISSUE TITLE
LevelUpScreen not executed

### ISSUE THREAD

**Issue by OnlyCharnel** [Shackless/unity-match3#6]
Der Levelup Screen wird korrekt gelesen, aber der zugehörige Mausklick nicht ausgeführt.

**Comment by OnlyCharnel** [comment]
Hier der Stacktrace vom Error:
Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei GowBot.Core.GemsOfWar.Screens.LevelUpScreen.FindBestTurn() in C:\Subversion\UnityMatch3\trunk\gowbot\GowBot.Core\GemsOfWar\Screens\LevelUpScreen.cs:Zeile 27.
   bei GowBot.Core.Bot.Bot.Tick() in C:\Subversion\UnityMatch3\trunk\gowbot\GowBot.Core\Bot\Bot.cs:Zeile 52.

**Comment by Shackless** [comment]
Das bedeutet, dass die OCR für das Dictionary aller aktuellen Mastery Levels oder der aktuell angebotenen in ImageHandler/ReadLevelUpScreen nicht funktioniert hat. Da müsstest du mal durchsteppen und schauen. Welche Auflösung hast du benutzt?
