### ISSUE TITLE
Enemy borders not detected => target lock

### ISSUE THREAD

**Issue by Shackless** [Shackless/unity-match3#7]
Enemy borders are detected as Rectangle.Empty resulting in a target lock loop.

![kaputt](https://user-images.githubusercontent.com/306996/44622611-20a80380-a8bc-11e8-90cb-360f3059f3bd.png)

**Comment by OnlyCharnel** [comment]
I found an issue of the blobfilter integrated into BlobCounter is not working. I found repeatedly a blob with width = 1 even with min Width set to 18. An additional .Where condition in the foreach helps to filter out those unwanted blobs.

**Comment by Shackless** [comment]
Okay, if tested feel free to create a pull request for the fix.
